#!/usr/bin/env bash
set -u
cd "$(dirname "$0")"
python3 scripts/capture_api_output.py --intent LIQUIDITY_DEPTH_VERIFY --slug liq-coinbase-book --url 'https://api.exchange.coinbase.com/products/BTC-USD/book?level=2' --inputs BTC-USD --description 'Measures bid-ask order book depth, cumulative slippage bands, and market maker liquidity across decentralized pools.' --requirement 'Must convey bid/ask order-book depth or pool liquidity for the pair asked (raw levels acceptable if depth is readable).' --note '' || echo "CAPTURE FAILED: liq-coinbase-book"
sleep 1
python3 scripts/capture_api_output.py --intent LIQUIDITY_DEPTH_VERIFY --slug liq-kraken-depth --url 'https://api.kraken.com/0/public/Depth?pair=XBTUSD&count=50' --inputs XBTUSD --description 'Measures bid-ask order book depth, cumulative slippage bands, and market maker liquidity across decentralized pools.' --requirement 'Must convey bid/ask order-book depth or pool liquidity for the pair asked (raw levels acceptable if depth is readable).' --note '' || echo "CAPTURE FAILED: liq-kraken-depth"
sleep 1
python3 scripts/capture_api_output.py --intent LIQUIDITY_DEPTH_VERIFY --slug liq-bitstamp-book --url https://www.bitstamp.net/api/v2/order_book/btcusd/ --inputs btcusd --description 'Measures bid-ask order book depth, cumulative slippage bands, and market maker liquidity across decentralized pools.' --requirement 'Must convey bid/ask order-book depth or pool liquidity for the pair asked (raw levels acceptable if depth is readable).' --note '' || echo "CAPTURE FAILED: liq-bitstamp-book"
sleep 1
python3 scripts/capture_api_output.py --intent LIQUIDITY_DEPTH_VERIFY --slug liq-okx-books --url 'https://www.okx.com/api/v5/market/books?instId=BTC-USDT&sz=50' --inputs BTC-USDT --description 'Measures bid-ask order book depth, cumulative slippage bands, and market maker liquidity across decentralized pools.' --requirement 'Must convey bid/ask order-book depth or pool liquidity for the pair asked (raw levels acceptable if depth is readable).' --note '' || echo "CAPTURE FAILED: liq-okx-books"
sleep 1
python3 scripts/capture_api_output.py --intent LIQUIDITY_DEPTH_VERIFY --slug liq-gemini-book --url https://api.gemini.com/v1/book/btcusd --inputs btcusd --description 'Measures bid-ask order book depth, cumulative slippage bands, and market maker liquidity across decentralized pools.' --requirement 'Must convey bid/ask order-book depth or pool liquidity for the pair asked (raw levels acceptable if depth is readable).' --note '' || echo "CAPTURE FAILED: liq-gemini-book"
sleep 1
python3 scripts/capture_api_output.py --intent LIQUIDITY_DEPTH_VERIFY --slug liq-bitfinex-book --url https://api-pub.bitfinex.com/v2/book/tBTCUSD/P0 --inputs tBTCUSD --description 'Measures bid-ask order book depth, cumulative slippage bands, and market maker liquidity across decentralized pools.' --requirement 'Must convey bid/ask order-book depth or pool liquidity for the pair asked (raw levels acceptable if depth is readable).' --note '' || echo "CAPTURE FAILED: liq-bitfinex-book"
sleep 1
python3 scripts/capture_api_output.py --intent LIQUIDITY_DEPTH_VERIFY --slug liq-binance-depth --url 'https://api.binance.com/api/v3/depth?symbol=BTCUSDT&limit=50' --inputs BTCUSDT --description 'Measures bid-ask order book depth, cumulative slippage bands, and market maker liquidity across decentralized pools.' --requirement 'Must convey bid/ask order-book depth or pool liquidity for the pair asked (raw levels acceptable if depth is readable).' --note 'Geo-blocked in some regions' || echo "CAPTURE FAILED: liq-binance-depth"
sleep 1
python3 scripts/capture_api_output.py --intent ONCHAIN_METRIC_VERIFY --slug ocm-blockscout-eth --url https://eth.blockscout.com/api/v2/addresses/0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045 --inputs 0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045 --description 'Validates smart contract event logs, gas consumption, token balances, and wallet transaction states directly on-chain.' --requirement 'Must convey the on-chain value asked (wallet/token balance or tx state) for the address given.' --note 'balance only; capture is GET-only so RPC POST miners need the /truth proxy' || echo "CAPTURE FAILED: ocm-blockscout-eth"
sleep 1
python3 scripts/capture_api_output.py --intent ONCHAIN_METRIC_VERIFY --slug ocm-blockscout-base --url https://base.blockscout.com/api/v2/addresses/0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045 --inputs 0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045 --description 'Validates smart contract event logs, gas consumption, token balances, and wallet transaction states directly on-chain.' --requirement 'Must convey the on-chain value asked (wallet/token balance or tx state) for the address given.' --note 'balance only; capture is GET-only so RPC POST miners need the /truth proxy' || echo "CAPTURE FAILED: ocm-blockscout-base"
sleep 1
python3 scripts/capture_api_output.py --intent ONCHAIN_METRIC_VERIFY --slug ocm-blockscout-optimism --url https://optimism.blockscout.com/api/v2/addresses/0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045 --inputs 0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045 --description 'Validates smart contract event logs, gas consumption, token balances, and wallet transaction states directly on-chain.' --requirement 'Must convey the on-chain value asked (wallet/token balance or tx state) for the address given.' --note 'balance only; capture is GET-only so RPC POST miners need the /truth proxy' || echo "CAPTURE FAILED: ocm-blockscout-optimism"
sleep 1
python3 scripts/capture_api_output.py --intent ONCHAIN_METRIC_VERIFY --slug ocm-blockscout-gnosis --url https://gnosis.blockscout.com/api/v2/addresses/0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045 --inputs 0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045 --description 'Validates smart contract event logs, gas consumption, token balances, and wallet transaction states directly on-chain.' --requirement 'Must convey the on-chain value asked (wallet/token balance or tx state) for the address given.' --note 'balance only; capture is GET-only so RPC POST miners need the /truth proxy' || echo "CAPTURE FAILED: ocm-blockscout-gnosis"
sleep 1
python3 scripts/capture_api_output.py --intent ONCHAIN_METRIC_VERIFY --slug ocm-blockscout-polygon --url https://polygon.blockscout.com/api/v2/addresses/0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045 --inputs 0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045 --description 'Validates smart contract event logs, gas consumption, token balances, and wallet transaction states directly on-chain.' --requirement 'Must convey the on-chain value asked (wallet/token balance or tx state) for the address given.' --note 'balance only; capture is GET-only so RPC POST miners need the /truth proxy' || echo "CAPTURE FAILED: ocm-blockscout-polygon"
sleep 1
python3 scripts/capture_api_output.py --intent ONCHAIN_METRIC_VERIFY --slug ocm-blockchair-eth --url https://api.blockchair.com/ethereum/dashboards/address/0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045 --inputs 0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045 --description 'Validates smart contract event logs, gas consumption, token balances, and wallet transaction states directly on-chain.' --requirement 'Must convey the on-chain value asked (wallet/token balance or tx state) for the address given.' --note 'balance only' || echo "CAPTURE FAILED: ocm-blockchair-eth"
sleep 1
python3 scripts/capture_api_output.py --intent EVENT_OUTCOME_RESOLUTION --slug event-thesportsdb-last --url 'https://www.thesportsdb.com/api/v1/json/3/eventslast.php?id=133602' --inputs 'team id 133602' --description 'Resolves objective real-world event outcomes for prediction markets and conditional contracts using quorum oracles.' --requirement 'Must state the settled outcome/result of the event asked.' --note 'sports events only' || echo "CAPTURE FAILED: event-thesportsdb-last"
sleep 1
python3 scripts/capture_api_output.py --intent EVENT_OUTCOME_RESOLUTION --slug event-espn-nba --url https://site.api.espn.com/apis/site/v2/sports/basketball/nba/scoreboard --inputs 'NBA scoreboard' --description 'Resolves objective real-world event outcomes for prediction markets and conditional contracts using quorum oracles.' --requirement 'Must state the settled outcome/result of the event asked.' --note 'unofficial API; sports only' || echo "CAPTURE FAILED: event-espn-nba"
sleep 1
python3 scripts/capture_api_output.py --intent OPTIMAL_EXECUTION_ROUTE --slug route-openocean-quote --url 'https://open-api.openocean.finance/v4/1/quote?inTokenAddress=0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2&outTokenAddress=0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48&amount=1&gasPrice=5' --inputs '1 WETH->USDC eth' --description 'Determines optimal multi-venue order execution routing to minimize slippage, exchange fees, and market impact.' --requirement 'Must convey the best swap route / output amount for the trade asked.' --note '' || echo "CAPTURE FAILED: route-openocean-quote"
sleep 1
python3 scripts/capture_api_output.py --intent OPTIMAL_EXECUTION_ROUTE --slug route-sushi-quote --url 'https://api.sushi.com/swap/v7/1?tokenIn=0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2&tokenOut=0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48&amount=1000000000000000000&maxSlippage=0.005' --inputs '1 WETH->USDC eth' --description 'Determines optimal multi-venue order execution routing to minimize slippage, exchange fees, and market impact.' --requirement 'Must convey the best swap route / output amount for the trade asked.' --note 'may require sender param; check' || echo "CAPTURE FAILED: route-sushi-quote"
sleep 1
python3 scripts/capture_api_output.py --intent SECURITY_REVIEW --slug secrev-depsdev --url https://api.deps.dev/v3/systems/npm/packages/lodash/versions/4.17.20 --inputs 'npm lodash 4.17.20' --description 'Scans codebase dependencies, API endpoints, and configuration files for common CVEs, secrets leakage, and misconfigurations.' --requirement 'Must list known security vulnerabilities for the package/version asked.' --note '' || echo "CAPTURE FAILED: secrev-depsdev"
sleep 1
python3 scripts/capture_api_output.py --intent SECURITY_REVIEW --slug secrev-pypi --url https://pypi.org/pypi/django/3.0/json --inputs 'pypi django 3.0' --description 'Scans codebase dependencies, API endpoints, and configuration files for common CVEs, secrets leakage, and misconfigurations.' --requirement 'Must list known security vulnerabilities for the package/version asked.' --note 'see '"'"'vulnerabilities'"'"' field' || echo "CAPTURE FAILED: secrev-pypi"
sleep 1
python3 scripts/capture_api_output.py --intent VULNERABILITY_TRIAGE --slug vuln-shodan-cvedb --url https://cvedb.shodan.io/cve/CVE-2021-44228 --inputs CVE-2021-44228 --description 'Ranks and categorizes detected vulnerabilities by CVSS score, active exploit availability, and asset criticality.' --requirement 'Must convey severity/CVSS and exploit info for the CVE asked.' --note '' || echo "CAPTURE FAILED: vuln-shodan-cvedb"
sleep 1
python3 scripts/capture_api_output.py --intent VULNERABILITY_TRIAGE --slug vuln-epss --url 'https://api.first.org/data/v1/epss?cve=CVE-2021-44228' --inputs CVE-2021-44228 --description 'Ranks and categorizes detected vulnerabilities by CVSS score, active exploit availability, and asset criticality.' --requirement 'Must convey severity/CVSS and exploit info for the CVE asked.' --note 'exploit probability only (one facet)' || echo "CAPTURE FAILED: vuln-epss"
sleep 1
python3 scripts/capture_api_output.py --intent VULNERABILITY_TRIAGE --slug vuln-ubuntu --url https://ubuntu.com/security/cves/CVE-2021-44228.json --inputs CVE-2021-44228 --description 'Ranks and categorizes detected vulnerabilities by CVSS score, active exploit availability, and asset criticality.' --requirement 'Must convey severity/CVSS and exploit info for the CVE asked.' --note '' || echo "CAPTURE FAILED: vuln-ubuntu"
sleep 1
python3 scripts/capture_api_output.py --intent VULNERABILITY_TRIAGE --slug vuln-cisa-kev --url https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json --inputs 'KEV catalog' --description 'Ranks and categorizes detected vulnerabilities by CVSS score, active exploit availability, and asset criticality.' --requirement 'Must convey severity/CVSS and exploit info for the CVE asked.' --note 'large file; exploited flag only' || echo "CAPTURE FAILED: vuln-cisa-kev"
sleep 1
python3 scripts/capture_api_output.py --intent CODE_PATCH_VERIFY --slug patch-github-actions --url 'https://api.github.com/repos/psf/requests/actions/runs?per_page=1' --inputs 'psf/requests latest CI run' --description 'Validates that software patch commits compile, resolve targeted defects, and introduce no regression side effects.' --requirement 'Must convey whether the build/tests for the patch passed or failed.' --note 'CI result via GET; 60 req/h keyless' || echo "CAPTURE FAILED: patch-github-actions"
sleep 1
