#!/usr/bin/env python3
"""Write INTENT_API_MINERS.md from out/intent-yaml-manifest.json.

Run after scripts/gen-intent-miner-yamls.py.
"""
from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

MC = Path(__file__).resolve().parents[1]
MANIFEST = MC / "out" / "intent-yaml-manifest.json"
DOC = MC / "INTENT_API_MINERS.md"

AUTH_LABEL = {
    "none": "no key",
    "free_key": "free key",
    "oauth": "OAuth",
    "self_host": "self-host",
    "paid": "paid",
}


def main() -> int:
    rows = json.loads(MANIFEST.read_text())
    by_intent: dict[str, list[dict]] = defaultdict(list)
    for r in rows:
        by_intent[r["catalog_intent"]].append(r)

    total = len(rows)
    intents = len(by_intent)
    no_key = sum(1 for r in rows if r["auth"] == "none")
    verified = sum(1 for r in rows if r["live_verified"])
    with_fields = sum(1 for r in rows if r["input_fields"])
    aliased = sorted({r["catalog_intent"] for r in rows if r["canonical_alias_applied"]})
    blocked = sorted(
        {
            r["catalog_intent"]
            for r in rows
            if not r["canonical_alias_applied"] and r["catalog_intent"] != r["registered_intent"]
        }
    )

    out: list[str] = []
    out.append("# Intent → API miners")
    out.append("")
    out.append("Generated by `scripts/gen-intent-miner-yamls.py` from `apiRegistry/*.json`.")
    out.append("One miner YAML per (intent, API provider) pair, under `intentYamls/<intent>/`.")
    out.append("")
    out.append("| Metric | Value |")
    out.append("|--------|-------|")
    out.append(f"| Intents covered | **{intents}** |")
    out.append(f"| Miner YAMLs | **{total}** |")
    out.append(f"| Providers needing no API key | **{no_key}** |")
    out.append(f"| Endpoints live-verified with a real call | **{verified}** |")
    out.append(f"| YAMLs exposing Direct Request input fields | **{with_fields}** |")
    out.append("")
    out.append("## Input fields in the Alexandria UI")
    out.append("")
    out.append(
        "Every YAML carries an `input_schema` listing the parameters that API needs, so the "
        "Direct Request panel renders a field per parameter with a working default prefilled. "
        "`param_map` translates the UI field name to the upstream parameter name where they differ "
        "(for example `lat` → `latitude`)."
    )
    out.append("")

    if aliased:
        out.append("## Canonical intent remapping")
        out.append("")
        out.append(
            "The node rejects any intent absent from the on-chain canonical registry. "
            "These catalog intents are registered under a canonical equivalent; the catalog name "
            "is preserved in each YAML's description and in the manifest."
        )
        out.append("")
        out.append("| Catalog intent | Registered as |")
        out.append("|----------------|---------------|")
        seen = set()
        for r in rows:
            if r["canonical_alias_applied"] and r["catalog_intent"] not in seen:
                seen.add(r["catalog_intent"])
                out.append(f"| `{r['catalog_intent']}` | `{r['registered_intent']}` |")
        out.append("")

    if blocked:
        out.append("## Not registerable yet")
        out.append("")
        out.append(
            "No honest canonical equivalent exists for these. The YAMLs are complete, but "
            "registration needs governance to call `addIntent()` on the diamond first."
        )
        out.append("")
        for i in blocked:
            out.append(f"- `{i}`")
        out.append("")

    out.append("## Per-intent providers")
    out.append("")
    for intent in sorted(by_intent):
        group = by_intent[intent]
        reg = group[0]["registered_intent"]
        head = f"### {intent}"
        if reg != intent:
            head += f"  (registered as `{reg}`)"
        out.append(head)
        out.append("")
        out.append(f"{group[0]['category']} · {len(group)} providers")
        out.append("")
        out.append("| # | Provider | Auth | Verified | Endpoint | UI input fields | YAML |")
        out.append("|---|----------|------|----------|----------|-----------------|------|")
        for n, r in enumerate(sorted(group, key=lambda x: (x["auth"] != "none", x["provider"])), 1):
            fields = ", ".join(f"`{f}`" for f in r["input_fields"]) or "—"
            endpoint = f"`{r['method']} {r['base_url']}{r['external_path']}`"
            out.append(
                f"| {n} | [{r['provider']}]({r['docs'] or r['base_url']}) "
                f"| {AUTH_LABEL.get(r['auth'], r['auth'])} "
                f"| {'yes' if r['live_verified'] else '—'} "
                f"| {endpoint} | {fields} | `{Path(r['file']).name}` |"
            )
        out.append("")

    DOC.write_text("\n".join(out) + "\n")
    print(f"wrote {DOC} ({intents} intents, {total} miners)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
