p() { n="$1"; shift; out=$(curl -sS -m 25 -o ./b8.bin -w "%{http_code}" "$@" 2>./e8.txt); echo "$n -> $out : $(head -c 130 ./b8.bin 2>/dev/null | tr -d '\0' | tr -c '[:print:]' ' ') $(head -c 60 ./e8.txt)"; rm -f ./b8.bin; }
p github-models -X POST -H "Content-Type: application/json" -d '{"model":"openai/gpt-4o-mini","messages":[{"role":"user","content":"hi"}]}' "https://models.github.ai/inference/chat/completions"
p novita -X POST -H "Content-Type: application/json" -d '{"model":"meta-llama/llama-3.1-8b-instruct","messages":[{"role":"user","content":"hi"}]}' "https://api.novita.ai/v3/openai/chat/completions"
p novita-v1 -X POST -H "Content-Type: application/json" -d '{"model":"meta-llama/llama-3.1-8b-instruct","messages":[{"role":"user","content":"hi"}]}' "https://api.novita.ai/openai/v1/chat/completions"
p cerebras -X POST -H "Content-Type: application/json" -d '{"model":"llama3.1-8b","messages":[{"role":"user","content":"hi"}]}' "https://api.cerebras.ai/v1/chat/completions"
p sambanova -X POST -H "Content-Type: application/json" -d '{"model":"Meta-Llama-3.1-8B-Instruct","messages":[{"role":"user","content":"hi"}]}' "https://api.sambanova.ai/v1/chat/completions"
p nebius -X POST -H "Content-Type: application/json" -d '{"model":"meta-llama/Meta-Llama-3.1-8B-Instruct","messages":[{"role":"user","content":"hi"}]}' "https://api.studio.nebius.com/v1/chat/completions"
p hyperbolic -X POST -H "Content-Type: application/json" -d '{"model":"meta-llama/Meta-Llama-3.1-8B-Instruct","messages":[{"role":"user","content":"hi"}]}' "https://api.hyperbolic.xyz/v1/chat/completions"
p chutes -X POST -H "Content-Type: application/json" -d '{"model":"deepseek-ai/DeepSeek-V3","messages":[{"role":"user","content":"hi"}]}' "https://llm.chutes.ai/v1/chat/completions"
p fireworks -X POST -H "Content-Type: application/json" -d '{"model":"accounts/fireworks/models/llama-v3p1-8b-instruct","messages":[{"role":"user","content":"hi"}]}' "https://api.fireworks.ai/inference/v1/chat/completions"
p together -X POST -H "Content-Type: application/json" -d '{"model":"meta-llama/Llama-3.3-70B-Instruct-Turbo","messages":[{"role":"user","content":"hi"}]}' "https://api.together.xyz/v1/chat/completions"
p deepinfra-chat -X POST -H "Content-Type: application/json" -d '{"model":"meta-llama/Meta-Llama-3.1-8B-Instruct","messages":[{"role":"user","content":"hi"}]}' "https://api.deepinfra.com/v1/openai/chat/completions"
p nlpcloud-semsim -X POST -H "Content-Type: application/json" -d '{"sentences":["a","b"]}' "https://api.nlpcloud.io/v1/paraphrase-multilingual-mpnet-base-v2/semantic-similarity"
p nlpcloud-kwkp -X POST -H "Content-Type: application/json" -d '{"text":"hello world"}' "https://api.nlpcloud.io/v1/fast-gpt-j/kw-kp-extraction"
p edenai-keywords -X POST -H "Content-Type: application/json" -d '{"providers":"amazon","text":"hello","language":"en"}' "https://api.edenai.run/v2/text/keyword_extraction"
p expertai-relevants -X POST -H "Content-Type: application/json" -d '{"document":{"text":"hello"}}' "https://nlapi.expert.ai/v2/analyze/standard/en/relevants"
p dandelion-sim "https://api.dandelion.eu/datatxt/sim/v1?text1=a&text2=b"
p meaningcloud-topics -X POST -d "lang=en&txt=hello&tt=a" "https://api.meaningcloud.com/topics-2.0"
p textrazor -X POST -d "text=hello&extractors=topics" "https://api.textrazor.com/"
p witai "https://api.wit.ai/message?v=20230215&q=hello"
p cohere-classify -X POST -H "Content-Type: application/json" -d '{"inputs":["hi"],"examples":[{"text":"a","label":"x"}]}' "https://api.cohere.com/v1/classify"
